### ISSUE TITLE
traverse more than 2 pages of an org's members

### ISSUE THREAD

**Issue by dsernst** [alexanderGugel/follow-me#3]
It looks like this only grabs the first 200 members in an organization: https://github.com/alexanderGugel/follow-me/blob/master/spam.js#L40

Would it be useful to try to grab the total number of users first, and then iterate through the appropriate number of pages?

**Comment by alexanderGugel** [comment]
Definitely. Feel free to send a PR.

**Comment by alexanderGugel** [comment]
This project is deprecated.
